version: '3'
services:
    web:
        build: ./web_app
        container_name: main_web
        ports:
            - 5036:5000
        volumes:
            - ./data/data_file.json:/datafile.json
        depends_on:
            - redis
    redis:
        image: redis:latest
        ports:
            - 6416:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
