---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewang-hw7-worker
  labels:
    app: ewang-hw7-worker
    username: ewang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ewang-hw7-worker
  template:
    metadata:
      labels:
        app: ewang-hw7-worker
        username: ewang
    spec:
      containers:
        - name: ewang-hw7-worker
          imagePullPolicy: Always
          image: cobcannon123/ewang-hw7:latest
          command: ["python3", "worker.py"]
          env:
            - name: REDIS_IP
              value: 10.99.12.229