---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewang-test-flask-deployment
  labels:
    app: ewang-test-flask
    username: ewang
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ewang-test-flask
  template:
    metadata:
      labels:
        app: ewang-test-flask
        username: ewang
        env: test
    spec:
      containers:
        - name: hello-flask
          imagePullPolicy: Never
          image: cobcannon123/kube-animals:1.0
          env:
          - name: FLASK_APP
            value: "app.py"
          ports:
          - name: http
            containerPort: 5000
          





