---
apiVersion: v1
kind: Service
metadata:
  name: ewang-test-flask-service
  labels:
    username: ewang
    env: test
spec:
  type: ClusterIP
  selector:
    app: ewang-test-flask
  ports:
  - name: hello-flask-service
    port: 5000
    targetPort: 5000